name: ApexParser Auto-Check

on:
  schedule:
    - cron: '0 * * * *' # Запуск каждый час
  workflow_dispatch: # Позволяет запускать вручную кнопкой

jobs:
  run-parser:
    runs-on: ubuntu-latest

    steps:
    - name: Проверка репозитория
      uses: actions/checkout@v4

    - name: Установка Python
      uses: actions/setup-python@v5
      with:
        python-node: '3.10'

    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Запуск чекера
      run: python checker.py

    - name: Сохранение результатов в GitHub
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add alive_bs.txt alive_cs.txt alive_mixed.txt
        git diff --quiet && git diff --staged --quiet || (git commit -m Automatic update" && git push)
