name: Update Subscriptions

on:
  schedule:
    - cron: '0 */4 * * *' # Автозапуск каждые 4 часа
  workflow_dispatch: # Кнопка для ручного запуска в меню Actions

permissions:
  contents: write # Важно! Разрешает скрипту сохранять и обновлять файлы в репозитории

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

#      - name: Create source files from Secrets
#        run: |
#         echo "${{ secrets.SOURCES_WL }}" > sources_wl.txt
#         echo "${{ secrets.SOURCES_BL }}" > sources_bl.txt

      - name: Run parser
        run: python parser.py

    #  - name: Clean secrets files before commit
     #   run: |
      #    rm -f sources_wl.txt sources_bl.txt

      - name: Commit and Push Changes
        run: |
          # Прописываем официального системного бота GitHub
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git add alive_full.txt alive_bs.txt alive_bl.txt
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update subscriptions [skip ci]" && git push)
