name: Update Proxies

on:
  schedule:
    - cron: '0 */6 * * *' # Запускать каждые 6 часов
  workflow_dispatch: # Появится кнопка ручного запуска

jobs:
  update-proxies:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run parser
        run: python parser.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add alive_full.txt alive_bs.txt alive_bl.txt sources_wl.txt sources_bl.txt
          git commit -m "Auto-update proxies" || exit 0
          git push
